### ISSUE TITLE
Unable to run browse-kill-ring

### ISSUE THREAD

**Issue by mgoldenbe** [browse-kill-ring/browse-kill-ring#62]
In Emacs 24.5.1 (running with minimal configuration), after installing the package, the command is not working. The error message is:

`font-lock-set-defaults: Wrong type argument: symbolp, (font-lock-fontify-region-function . browse-kill-ring-fontify-region) `

**Comment by T-J-Teru** [comment]
I just pushed a new commit 8debc43e41d7e51532698331c6f283905890b904 which I think will fix this issue.  I don't have access to any emacs before 25 right now, so can't test this.  Feel free to give this a try and let me know if the issue is resolved.  Otherwise I'll try to confirm the issue fixed tomorrow.

**Comment by mgoldenbe** [comment]
This commit has not made it to Melpa yet. So, I hope to try it out tomorrow...

**Comment by T-J-Teru** [comment]
I've now tested this against emacs 24.5.  I reproduced the failure when commit 8debc43 is removed, and can confirm it works when commit 8debc43 is added.
